[tools]
node = "18.18.0"
bun = 'latest'
yarn = 'latest'

neovim = 'ref:master'
git = 'latest'
lazygit = 'latest'
gitconfig = 'latest'
gitui = 'latest'
github-cli = 'latest'
lua = 'latest'
zig = 'latest'

dotnet = 'latest'
go = 'latest'
python = "3.12.4"
rust = 'latest'
ruby = '3.1.0'

dockle = 'latest'
helm = 'latest'
kubectl = '1.28.10'
kubie = 'latest'
kustomize = ' latest'
kubelogin = 'latest'
kops = 'latest'
kind = 'latest'
minikube = 'latest'
argo = 'latest'
argocd = "2.11.7"
azure-cli = 'latest'
terraform = 'latest'

ripgrep = 'latest'
fd = 'latest'
tree-sitter = 'latest'
glab = 'latest'
starship = "latest"
deno = "latest"
"npm:degit" = "2.8.4"
"npm:joplin" = "3.0.1"
# [plugins]
# git = 'https://gitlab.com/jcaigitlab/asdf-git'

[tasks.cleancache]
alias = "c"
run = "rm -rf .cache"
hide = false
[tasks.pipup]
alias = "p"
run = "pip install --upgrade pip && pip install pygobject"
hide = false

[tasks.update]
run = "mise up"
hide = false
[tasks.addon]
depends = ["cleancache", "update", "pipup"]
alias = "a"
run = "mise use -g npm:degit@latest && mise use -g npm:joplin@latest"
hide = false

# [env]
# _.python.venv = "~/venv"
# _.python.venv = { path = "{{env.HOME}}/venv", create = true }

[settings]
legacy_version_file = true
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '1 week'
trusted_config_paths = ['~/.config/mise/config.toml']
verbose = false
asdf_compat = true
http_timeout = 120
jobs = 20
raw = false
yes = true
not_found_auto_install = true
task_output = 'prefix'
paranoid = false
disable_default_shorthands = false
experimental = true
status = { missing_tools = 'if_other_versions_installed', show_env = false, show_tools = false }
python_compile = false
